title: JF Lab
description: Neurobiology Laboratory at the Hospital for Sick Children

# Header Image
# To change the header background image, please rename your file header.png and
# place in the img/ folder

headlineMain: Welcome to the Josselyn Frankland Lab
headlineSmall:  Neurobiology Laboratory at the Hospital for Sick Children

#Research Themes


#Site Categories
category:
  - publications
  - photos
  - announcements
  - misc

#Settings, don't change typically
markdown: kramdown
permalink: /:categories/:year/:title.html
future: true

exclude: [pdfs]
keep_files: [pdfs]

gems:
  - jemoji
  - jekyll-twitter-plugin
