name: Update Lab Members 

on:
  push:
    branches:
      - master

jobs:
  fetch-changes:
    name: Update member listing

    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - name: set-up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client pandas

      - name: Decrypt Google Credentials
        run: ./.github/scripts/decrypt_cred.sh
        env:
          CREDENTIALS_PASS: ${{ secrets.CREDENTIALS_PASS }}
      
      - name: Fetch and update member listing
        run: |
          python ./update_members.py $HOME/secrets/credentials.json

      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update members
          branch: ${{ github.head_ref }}
          commit_user_name: GitHub Actions
          commit_user_email: action@github.com
          commit_author: Author <actions@github.com>
